# Generated by Django 3.0.8 on 2021-10-25 20:01

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1)),
                ('price', models.IntegerField()),
                ('date', models.DateField(default=datetime.datetime(2021, 10, 25, 20, 1, 55, 603338))),
                ('Customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Shop.Customer')),
                ('Product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Shop.Product')),
            ],
        ),
    ]
