# Generated by Django 3.0.8 on 2021-10-25 20:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0003_auto_20211025_2004'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='adresse',
            field=models.CharField(blank=True, default=' ', max_length=50),
        ),
        migrations.AddField(
            model_name='order',
            name='phone',
            field=models.CharField(blank=True, default=' ', max_length=50),
        ),
        migrations.AlterField(
            model_name='order',
            name='date',
            field=models.DateField(default=datetime.datetime(2021, 10, 25, 20, 13, 2, 913419)),
        ),
    ]
