# Generated by Django 3.0.8 on 2021-11-06 18:49

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0007_auto_20211029_2048'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='date',
            field=models.DateField(default=datetime.datetime(2021, 11, 6, 18, 49, 3, 617424, tzinfo=utc)),
        ),
    ]
